name: CI Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.73.0'
        extended: true
    - name: Build docs
      run: hugo --minify
      env:
        HUGO_ENV: production
    - name: Upload docs packages
      uses: actions/upload-artifact@v1
      with:
        name: slides-site
        path: public/
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public